security:
  basic:
    enabled: false

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true    
  thymeleaf: 
    cache: false
      
notification:
  service:
    non-production: 
      enabled: true
      to: 
      - some-to-mail-1@ca.com
      - some-to-mail-2@ca.com
      cc:
      - some-cc-mail-1@ca.com
      - some-cc-mail-2@ca.com
      - some-cc-mail-3@ca.com
      bcc:
      - some-bcc-mail-1@ca.com
    from: credit-approval@ca.com
    reply-to: credit-approval@ca.com
#    templates:
#      credit-approval: 
#        inline-images:
#          userImage: sg.png 